[DEFAULT]
version = 0.0.12
build = $(git rev-list --count HEAD)

[helpMessige]
developer = Justinas Stankūnas
email = IamJustStan@hotmail.com
repoURL = https://github.com/JustPause/KVM-bibliotekos-sistema.git
