[DEFAULT]
version = 0.0.13
build = $(git rev-list --count HEAD)

[helpMessige]
developer = Justinas Stankūnas
email = IamJustStan@hotmail.com
repourl = https://github.com/JustPause/KVM-bibliotekos-sistema.git

[userData]
isnbkoduatspauzdinimasiskur = /home/justinas/1235323441233
isnbkoduatspauzdinimasikur = 

