[DEFAULT]
version = 0.0.14
build = $(git rev-list --count HEAD)

[helpMessige]
developer = Justinas Stankūnas
email = IamJustStan@hotmail.com
repourl = https://github.com/JustPause/KVM-bibliotekos-sistema.git

[userData]
isnbkoduatspauzdinimas = /home/justinas/Programming/Valdorfas/KVM-bibliotekos-sistema/pdfs/NewFiles.pdf
kurtinaujusbarkodus = /home/justinas/Programming/Valdorfas/KVM-bibliotekos-sistema/pdfs/File.pdf
isklaveturosskaitytuvo = /home/justinas/Programming/Valdorfas/KVM-bibliotekos-sistema/pdfs/Data.csv
ieskotipagalpavadinima = /home/justpause/Programming/pyhton/KVM-bibliotekos-sistema
lentelessukurimas = /home/justpause/Programming/pyhton/KVM-bibliotekos-sistema
duomenuperkelimas = /home/justinas/Programming/Valdorfas/KVM-bibliotekos-sistema/csv/test2.csv

