[DEFAULT]
version = 0.1.1
build = $(git rev-list --count HEAD)

[helpMessige]
developer = Justinas Stankūnas
email = IamJustStan@hotmail.com
repourl = https://github.com/JustPause/KVM-bibliotekos-sistema.git

[userData]
isnbkoduatspauzdinimas = /home/justinas/Programming/Valdorfas/KVM-bibliotekos-sistema/pdfs/BarkodaiSpauzdinimui62132313213213213123223.pdf
kurtinaujusbarkodus = /home/justinas/Programming/Valdorfas/KVM-bibliotekos-sistema/pdfs/BarkodaiSpauzdinimui6.pdf
isklaveturosskaitytuvo = /home/justinas/Programming/Valdorfas/KVM-bibliotekos-sistema
ieskotipagalpavadinima = /home/justpause/Programming/pyhton/KVM-bibliotekos-sistema
lentelessukurimas = /home/justpause/Programming/pyhton/KVM-bibliotekos-sistema/csv/Testavimas.csv
duomenuperkelimas = /home/justpause/Programming/pyhton/KVM-bibliotekos-sistema/csv/Testavimas.csv

